### ISSUE TITLE
Please add support for connecting to Anthos clusters hosted outside GCP via the connect gateway

### ISSUE THREAD

**Issue by rob-whittle** [google-github-actions/get-gke-credentials#257]
### TL;DR

Hi, we have an Anthos cluster hosted on-prem that we can connect to using the connect gateway.  It seems this action does not work in this scenario as it requires a cluster location to be specified.  We have tried 'global' and 'registered' (which is what the location is listed as in GCP, see attached) but the action produces an error 'location does not exist'.
<img width="448" alt="image" src="https://user-images.githubusercontent.com/69803842/205121430-6368a07d-c14a-4528-8d14-ce0fba4281de.png">

**Comment by code-ape** [comment]
Just voicing that this would be very useful for myself as well. Thank you!

**Comment by sethvargo** [comment]
We are not planning to implement this feature.
