### ISSUE TITLE
Support gke-gcloud-auth-plugin

### ISSUE THREAD

**Issue by Markieta** [google-github-actions/get-gke-credentials#264]
### TL;DR

Need an option for using `gke-gcloud-auth-plugin` instead of `gcp auth plugin` or short-lived access tokens.

`use_auth_provider` fails on modern versions of GKE:

```bash
error: The gcp auth plugin has been removed.
Please use the "gke-gcloud-auth-plugin" kubectl/client-go credential plugin instead.
See https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke for further details
Error: Process completed with exit code 1.
```

**Comment by michaeldelago** [comment]
I'd consider this a bug, rather than an enhancement. If the auth plugin doesn't get added, kubectl will break.

**Comment by cobraz** [comment]
Hello 👋 

I've created a simple GitHub Action for this, feel free to use this until someone integrates `setup-gke-gcloud-auth-plugin` into `get-gke-credentials`. I'll try to keep users of `cobraz/setup-gke-gcloud-auth-plugin` updated on using `gke-gcloud-auth-plugin` with GitHub Actions as we go.

To get started, drop this in your workflow:

```yaml
- uses: cobraz/setup-gke-gcloud-auth-plugin@v1
```

Feel free to open issues and PRs here: https://github.com/cobraz/setup-gke-gcloud-auth-plugin

**Comment by chamini2** [comment]
Moving to google-github-actions v2 for all actions I need seem to work now for my use case.
