### ISSUE TITLE
Add input for location or better naming of the generated file

### ISSUE THREAD

**Issue by raphzandrade** [google-github-actions/get-gke-credentials#268]
### TL;DR

We utilize the action within a workflow that also commits and opens pull requests. Due to the fact that the generated file's name consists solely of a random hash, it is not possible to simply add it to our git ignore.  Adding something similar to `google-github-actions/auth@v1` would be a more effective solution.

![image](https://user-images.githubusercontent.com/16387849/228624034-6e96377c-5eaf-4b87-9766-ae2782780e5b.png)

**Comment by sethvargo** [comment]
Hi @raphzandrade - do you mean for the KUBECONFIG file?

**Comment by raphzandrade** [comment]
Hi, @sethvargo! Yes, the one created here:

`const kubeConfigPath = await writeSecureFile(randomFilepath(workspace), kubeConfig);`

I believe incorporating additional information here would be beneficial. Don't you think?

**Comment by sethvargo** [comment]
I think it would be best to do what you're doing (or `echo` that value into a gitignore). We won't break the output without a major version bump.

Changing the path name _could_ break people who might be depending on the location predictability.

**Comment by raphzandrade** [comment]
@sethvargo Is it possible to include this in a future version? I understand that it may disrupt the workflow for those who rely on location predictability, but I fail to see how adding something to the name (e.g `kubeconfig-randomhash`), would have that effect. Most of the logic likely relies on the path that is returned or set to the environment.

**Comment by raphzandrade** [comment]
Furthermore, adding an optional input to customize the location would not affect the logic for those who are unaware of the change since they would not have it included.
